// PROMPT VERSION: 4.0 — fully generative, zero scripted questions
import { callLLM, callLLMStream, parseJSON } from "../lib/llm.js";

export async function runJudgeOrchestrator({ transcript, sessionContext, history, currentQuestionIndex = 0 }) {
  const parsed = typeof sessionContext === "string" ? JSON.parse(sessionContext) : sessionContext;
  const { personas, sessionPlan, situation, researchContext } = parsed;

  // Build research block from agent outputs — this is the model's entire knowledge source
  const rc = researchContext || {};
  const researchBlock = [
    rc.interviewerPatterns  && `HOW THESE INTERVIEWERS BEHAVE: ${rc.interviewerPatterns}`,
    rc.successPatterns      && `WHAT WORKS FOR CANDIDATES: ${rc.successPatterns}`,
    rc.psychologicalProfile && `WHAT THE INTERVIEWER IS REALLY EVALUATING: ${rc.psychologicalProfile}`,
    rc.pushbackStyle        && `HOW THEY CHALLENGE CANDIDATES: ${rc.pushbackStyle}`,
    rc.diagnosedWeakness    && `USER'S WEAK SPOT TO PROBE: ${rc.diagnosedWeakness}`,
    rc.warningSignals?.length && `SIGNS USER IS STRUGGLING: ${rc.warningSignals.join("; ")}`,
    rc.keyFindings?.length  && `KEY RESEARCH INSIGHTS: ${rc.keyFindings.join(" | ")}`,
  ].filter(Boolean).join("\n");

  const turnCount = history.filter(t => t.speaker !== "heartbeat").length;
  const totalTurns = (sessionPlan?.totalEstimatedMinutes || 5) * 2; // ~2 exchanges per minute

  // ── Opening turn ─────────────────────────────────────────────────────────────
  if (!transcript && history.length === 0) {
    const p = personas[0];
    try {
      const raw = await callLLM({
        systemPrompt: `You are ${p.name}, ${p.role}. Style: ${p.style}
You are opening a live practice session for someone preparing for: "${situation}"
${researchBlock ? `\nResearch context:\n${researchBlock}\n` : ""}
Write your opening: introduce yourself in one sentence, then ask ONE sharp, specific question about this exact situation.
Do NOT ask generic questions like "what's at stake" or "what are you nervous about."
Draw from the research — ask something that shows you know this domain cold.
Return ONLY valid JSON: {"line": "your full opening"}`,
        userPrompt: `Situation: "${situation}"`,
        maxTokens: 160,
      });
      const result = parseJSON(raw);
      if (result?.line) {
        return { nextPersona: p.name, voiceId: p.voiceId, line: result.line, intent: "Opening", sessionAdvancing: false, sessionComplete: false, userPerformanceNote: "Session started" };
      }
    } catch (err) {
      console.error("[judge] opening error:", err.message);
    }
    return {
      nextPersona: p.name, voiceId: p.voiceId,
      line: `Hi, I'm ${p.name} — ${p.role}. I've reviewed everything. Let's get into it.`,
      intent: "Opening fallback", sessionAdvancing: false, sessionComplete: false, userPerformanceNote: "Session started",
    };
  }

  // ── Hard turn limit ───────────────────────────────────────────────────────────
  if (turnCount >= totalTurns + 4) {
    return {
      nextPersona: personas[0].name, voiceId: personas[0].voiceId,
      line: "That covers everything I wanted to explore. Thanks for your time.",
      intent: "Session end", sessionAdvancing: false, sessionComplete: true,
      userPerformanceNote: "Session completed",
    };
  }

  // ── Pick the active persona (rotate through the panel) ───────────────────────
  const personaIndex = Math.min(
    Math.floor((turnCount / Math.max(totalTurns, 1)) * personas.length),
    personas.length - 1
  );
  const activePerson = personas[personaIndex];

  // ── Detect pure greeting (≤4 words, starts with greeting word) ───────────────
  const trimmed = (transcript || "").trim();
  const isGreeting = trimmed.split(/\s+/).filter(Boolean).length <= 4 &&
    /^(hi+|hello+|hey+|good\s*(morning|afternoon|evening)|howdy)\b/i.test(trimmed);

  // ── Build fully generative system prompt ─────────────────────────────────────
  const difficultyHint = turnCount < 2
    ? "This is early in the session — start warm, build rapport."
    : turnCount >= totalTurns - 1
    ? "This is the final stretch — close with something that leaves them thinking."
    : currentQuestionIndex > 1
    ? "Mid-session — escalate. Push back on vague answers, dig into specifics."
    : "Building momentum — introduce a harder angle.";

  const systemPrompt = `You are ${activePerson.name}, ${activePerson.role}.
Style: ${activePerson.style}
You are running a live practice session for: "${situation}"

EVERYTHING YOU KNOW (generated by research agents — use this, not scripts):
${researchBlock || `This is a practice session for: "${situation}"`}

SESSION STATE: Turn ${turnCount + 1} of ~${totalTurns}. ${difficultyHint}

HOW TO RESPOND — strict rules:
1. React to the user's last message FIRST. Quote or reference something specific they said.
   - If strong: "You said X — that's the right instinct. Now push it further: ..."
   - If vague: "You mentioned X but stayed surface-level. What does that actually mean in practice?"
   - If stumbled: "You trailed off on X — that's exactly where I want to push."
   - If greeting: "Hey — I'm ${activePerson.name}. [then one sharp opening question based on the research]"
2. Generate your next move entirely from the conversation and research above. NO scripts.
3. Vary your approach — don't repeat angles already covered in the conversation.
4. Max 3 sentences. Every word must be specific to: "${situation}"

Return ONLY valid JSON:
{
  "nextPersona": "${activePerson.name}",
  "voiceId": "${activePerson.voiceId}",
  "line": "your response — react + advance",
  "intent": "what this turn tests",
  "sessionAdvancing": true or false,
  "sessionComplete": true or false,
  "userPerformanceNote": "honest 1-line note on how they did"
}
sessionComplete: true only when all major angles have been thoroughly covered (typically after turn ${totalTurns})`;

  const recentHistory = history.slice(-10).map(t => `${t.speaker}: ${t.text}`).join("\n");

  const userPrompt = `CONVERSATION SO FAR:
${recentHistory}

USER JUST SAID: "${transcript}"
${isGreeting ? "⚠️ This is a pure greeting — introduce yourself warmly, then ask one research-grounded opening question." : ""}

Generate your next response. React to what they said. Use the research. Do not repeat questions already asked.`;

  // ── LLM call ─────────────────────────────────────────────────────────────────
  let raw;
  try {
    raw = await callLLMStream({ systemPrompt, userPrompt, maxTokens: 500, onChunk: () => {} });
  } catch (err) {
    console.error("[judge] LLM error:", err.message);
    // Recovery: minimal call that still reacts to what they said
    try {
      const recoverRaw = await callLLM({
        systemPrompt: `You are ${activePerson.name}, ${activePerson.role} in a practice session about: "${situation}".
${isGreeting ? "They are greeting you — introduce yourself warmly and ask one opening question about the situation." : "React to what they said and ask one specific follow-up. Reference something from their words."}
2 sentences max. Return ONLY JSON: {"line": "..."}`,
        userPrompt: `They said: "${transcript}"\nConversation:\n${recentHistory}`,
        maxTokens: 120,
      });
      const recoverResult = parseJSON(recoverRaw);
      if (recoverResult?.line) {
        return { nextPersona: activePerson.name, voiceId: activePerson.voiceId, line: recoverResult.line, intent: "Recovery", sessionAdvancing: false, sessionComplete: false, userPerformanceNote: "LLM recovery" };
      }
    } catch {}
    // True last resort — echo their words back
    const userWords = trimmed.split(/\s+/).slice(0, 6).join(" ");
    return {
      nextPersona: activePerson.name, voiceId: activePerson.voiceId,
      line: userWords ? `You mentioned "${userWords}" — say more about that.` : "Tell me more.",
      intent: "Last resort", sessionAdvancing: false, sessionComplete: false,
      userPerformanceNote: "LLM unavailable",
    };
  }

  const result = parseJSON(raw);
  if (!result?.line) {
    console.error("[judge] bad parse:", raw?.slice(0, 150));
    const userWords = trimmed.split(/\s+/).slice(0, 6).join(" ");
    return {
      nextPersona: activePerson.name, voiceId: activePerson.voiceId,
      line: userWords ? `You mentioned "${userWords}" — say more.` : "Tell me more.",
      intent: "Parse error fallback", sessionAdvancing: false, sessionComplete: false,
      userPerformanceNote: "Parse error",
    };
  }

  // Enforce 3-sentence max
  const sentences = result.line.match(/[^.!?]+[.!?]+/g) || [result.line];
  result.line = sentences.slice(0, 3).join(" ").trim();

  return result;
}
